version: "3"
services:
  hazelcast:
    image: hazelcast/hazelcast:5.2.0
    environment:
      JAVA_OPTS: -Dhazelcast.config=/opt/project/config/hazelcast.yaml
    volumes:
      - ".:/opt/project"

  mancenter:
    image: hazelcast/management-center:5.2.0
    environment:
      MC_DEFAULT_CLUSTER: dev
      MC_DEFAULT_CLUSTER_MEMBERS: hazelcast:5701
    ports:
      - "8080:8080"

  hazelcast-shell:
    image: hazelcast/hazelcast:5.2.0
    volumes:
      - ".:/opt/project"
    command: >
      hz-cli -v submit -c=com.hzsamples.automl.solution.PredictionPipeline
        -t=dev@hazelcast
        -n=fraud-prediction 
      /opt/project/scoring-pipeline/target/scoring-pipeline-1.0-SNAPSHOT.jar  
      /opt/project/scoring-pipeline/gcp-credentials.json 
      hazelcast-33 
      us-central1 
      6989362321306943488

  event-sender:
    build:
      context: event-sender
    command: python eventsender.py --dir data --tps 8 --hz-members hazelcast:5701
