apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-pipeline
spec:
  template:
    spec:
      containers:
      - name: deployer
        image: wrmay/automl_pipeline_deploy
        command:  
        - hz-cli 
        - submit 
        - -c=com.hzsamples.automl.PredictionPipeline 
        - -t=automl-hazelcast  
        - scoring-pipeline-1.0-SNAPSHOT.jar  
        - hazelcast-33 
        - us-central1 
        - "4731246912831750144"
      restartPolicy: Never


